Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -18,7 +18,6 @@ jobs:
         run: |
           docker compose -f docker-compose.yml config
 
-
   deploy:
     name: CD – Deploy to EC2
     runs-on: ubuntu-latest
@@ -40,20 +39,44 @@ jobs:
             echo "Connected user:"
             whoami
 
+            echo "Updating packages"
+            sudo apt update -y
+
+            echo "Checking Docker installation..."
+            if ! command -v docker &> /dev/null
+            then
+              echo "Docker not found. Installing Docker..."
+              sudo apt install -y docker.io
+              sudo systemctl enable --now docker
+              sudo usermod -aG docker ubuntu
+            else
+              echo "Docker already installed"
+            fi
+
+            echo "Checking Docker Compose installation..."
+            if ! command -v docker-compose &> /dev/null
+            then
+              echo "Docker Compose not found. Installing..."
+              sudo apt install -y docker-compose
+            else
+              echo "Docker Compose already installed"
+            fi
+
+            echo "Checking project directory..."
+            if [ ! -d "/home/ubuntu/Discover-Dollar-task" ]; then
+              echo "Project not found. Cloning repository..."
+              cd /home/ubuntu
+              git clone https://github.com/mangeshmule-devops/Discover-Dollar-task.git
+            fi
+
             echo "Going to project directory"
             cd /home/ubuntu/Discover-Dollar-task
+
+            echo "Pulling latest code"
             sudo git pull
 
-            echo "Files in directory:"
-            ls -la
-
-            echo "Docker versions:"
-            docker --version
-            docker-compose version
-
             echo "Deploying application"
-            docker-compose -f docker-compose.yml pull
-            docker-compose -f docker-compose.yml down
-            docker-compose -f docker-compose.yml up -d
+            sudo docker-compose down || true
+            sudo docker-compose up -d --build
 
             echo "Deployment completed successfully"
